---
title: "Team"
---

<br>

| Name | Degree | Dissertation/Thesis | Current Position |
|------|--------|---------------------|------------------|
| Amanda Dorsey | PhD | [To be added] | PhD Student |
| Oluseye Ogunmoroti | PhD | [To be added] | PhD Student |
| Zhaohua Zheng | PhD | [To be added] | PhD Student |
| Erin Rogers | PhD | Mediation for opioid use disorder during the perinatal period; effectiveness of buprenorphine versus methadone on the risk of overdose in pregnancy | [To be added] |
| Mundayi Nlandu | MPH | Machine learning algorithms to evaluate predictors of stillbirth; fetal to placental weight ratios as a marker of stillbirth in Norway | ORISE Fellow, Centers for Disease Control and Prevention |
| Jackie Rudolph | Postdoc | Advanced causal inference methods for reproductive, HIV/AIDS, and environmental epidemiology; causal intervention analysis, competing events, simulation, and generalization | Assistant Scientist in Epidemiology, Johns Hopkins University |
| Gabriel Conzuelo | PhD | Machine learning methods for effect measure modification, transportability of causal effects in randomized trials, and measurement error correction in perinatal epidemiology | Research Associate, Basic Health International, Pittsburgh, PA |
| Yongqi Zhong | PhD | Causal inference, causal discovery, graphical models, machine learning; applying advanced methods in observational studies and randomized trials | Senior Biostatistician, GRAIL, LLC |
| Ya-Hui Yu | PhD | Conceptual and methodological challenges on quantifying the impact of maternal incident obesity on perinatal mortality | Assistant Professor of Epidemiology, Georgia State University |

<br>
